version: "3.5"

services:
  app:
    build: .
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8005"]
    volumes:
      - ./app:/app
    ports:
      - "8005:8005"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
