# Generated by Django 3.2.10 on 2021-12-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField(null=True)),
                ('max_shifts_per_week', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_worker_name', models.CharField(max_length=255, null=True)),
                ('target_dt', models.DateTimeField()),
                ('updated_dt', models.DateTimeField(null=True)),
                ('memo', models.CharField(max_length=1024, null=True)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='time_management.worker')),
            ],
        ),
    ]
